apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: someapp.project-respite.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: project-respite.com
  # version name to use for REST API: /apis/<group>/<version>
  version: v1
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: someapp
    # singular name to be used as an alias on the CLI and for display
    singular: someapp
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: SomeApp
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - sma
  additionalPrinterColumns:
    - name: Image
      type: string
      description: Container Image URI.
      JSONPath: .spec.image
    - name: Replicas
      type: integer
      description: The number of replicas.
      JSONPath: .spec.replicas
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["image","replicas"]
          properties:
            image:
              type: string
            replicas:
              type: integer